export class FormConfig {
  getFormConfig(entity) {
    const configs = {
      creator: {
        title: 'Neuen Creator anlegen',
        fields: [
          { name: 'vorname', label: 'Vorname', type: 'text', required: true, validation: { type: 'text', minLength: 2 } },
          { name: 'nachname', label: 'Nachname', type: 'text', required: true, validation: { type: 'text', minLength: 2 } },
          { name: 'instagram', label: 'Instagram', type: 'text', required: false },
          { 
            name: 'instagram_follower', 
            label: 'Instagram Follower', 
            type: 'select', 
            required: false,
            options: [
              { value: '0-2500', label: '0 - 2.500' },
              { value: '2500-5000', label: '2.500 - 5.000' },
              { value: '5000-10000', label: '5.000 - 10.000' },
              { value: '10000-25000', label: '10.000 - 25.000' },
              { value: '25000-50000', label: '25.000 - 50.000' },
              { value: '50000-100000', label: '50.000 - 100.000' },
              { value: '100000-250000', label: '100.000 - 250.000' },
              { value: '250000-500000', label: '250.000 - 500.000' },
              { value: '500000-1000000', label: '500.000 - 1.000.000' },
              { value: '1000000+', label: '+ 1.000.000' }
            ]
          },
          { name: 'tiktok', label: 'TikTok', type: 'text', required: false },
          { 
            name: 'tiktok_follower', 
            label: 'TikTok Follower', 
            type: 'select', 
            required: false,
            options: [
              { value: '0-2500', label: '0 - 2.500' },
              { value: '2500-5000', label: '2.500 - 5.000' },
              { value: '5000-10000', label: '5.000 - 10.000' },
              { value: '10000-25000', label: '10.000 - 25.000' },
              { value: '25000-50000', label: '25.000 - 50.000' },
              { value: '50000-100000', label: '50.000 - 100.000' },
              { value: '100000-250000', label: '100.000 - 250.000' },
              { value: '250000-500000', label: '250.000 - 500.000' },
              { value: '500000-1000000', label: '500.000 - 1.000.000' },
              { value: '1000000+', label: '+ 1.000.000' }
            ]
          },
          {
            name: 'sprachen_ids',
            label: 'Sprachen',
            type: 'multiselect',
            required: false,
            options: [],
            dynamic: true,
            searchable: true,
            tagBased: true,
            placeholder: 'Sprachen suchen und hinzufügen...',
            table: 'sprachen',
            displayField: 'name',
            valueField: 'id',
            customField: true
          },
          {
            name: 'branche_ids',
            label: 'Branchen',
            type: 'multiselect',
            required: false,
            options: [],
            dynamic: true,
            searchable: true,
            tagBased: true,
            placeholder: 'Branchen suchen und hinzufügen...',
            table: 'branchen_creator',
            displayField: 'name',
            valueField: 'id',
            customField: true
          },
          {
            name: 'creator_type_ids',
            label: 'Creator-Typen',
            type: 'multiselect',
            required: false,
            options: [],
            dynamic: true,
            searchable: true,
            tagBased: true,
            placeholder: 'Creator-Typen suchen und hinzufügen...',
            table: 'creator_type',
            displayField: 'name',
            valueField: 'id',
            customField: true
          },
          { name: 'telefonnummer', label: 'Telefonnummer', type: 'tel', required: false, validation: { type: 'phone' } },
          { name: 'mail', label: 'Email', type: 'email', required: false, validation: { type: 'email' } },
          { name: 'portfolio_link', label: 'Portfolio Link', type: 'url', required: false, validation: { type: 'url' } },
          { name: 'lieferadresse_strasse', label: 'Straße', type: 'text', required: false },
          { name: 'lieferadresse_hausnummer', label: 'Hausnummer', type: 'text', required: false },
          { name: 'lieferadresse_plz', label: 'PLZ', type: 'text', required: false },
          { name: 'lieferadresse_stadt', label: 'Stadt', type: 'text', required: false },
          { name: 'lieferadresse_land', label: 'Land', type: 'text', required: false },
          { name: 'notiz', label: 'Notizen', type: 'textarea', required: false }
        ]
      },
      unternehmen: {
        title: 'Neues Unternehmen anlegen',
        fields: [
          { name: 'firmenname', label: 'Firmenname', type: 'text', required: true, validation: { type: 'text', minLength: 2 } },
          { name: 'logo_file', label: 'Logo', type: 'custom', customType: 'uploader', accept: 'image/png,image/jpeg', multiple: false, required: false },
          { name: 'branche_id', label: 'Branchen', type: 'multiselect', required: false, dynamic: true, searchable: true, tagBased: true, placeholder: 'Branche suchen und hinzufügen...', table: 'branchen', displayField: 'name', valueField: 'id', relationTable: 'unternehmen_branchen', relationField: 'branche_id' },
          { name: 'rechnungsadresse_strasse', label: 'Straße', type: 'text', required: false },
          { name: 'rechnungsadresse_hausnummer', label: 'Hausnummer', type: 'text', required: false },
          { name: 'rechnungsadresse_plz', label: 'PLZ', type: 'text', required: false },
          { name: 'rechnungsadresse_stadt', label: 'Stadt', type: 'text', required: false },
          { name: 'rechnungsadresse_land', label: 'Land', type: 'text', required: false },
          { name: 'invoice_email', label: 'Rechnungs-Email', type: 'email', required: false, validation: { type: 'email' } },
          { name: 'status', label: 'Status', type: 'select', required: false, options: ['Aktiv', 'Inaktiv', 'Prospekt'] }
        ]
      },
      kampagne: {
        title: 'Neue Kampagne anlegen',
        fields: [
          { 
            name: 'kampagnenname', 
            label: 'Kampagnenname', 
            type: 'text', 
            required: false, // Nicht required da automatisch generiert
            validation: { type: 'text', minLength: 2, skipIfAutoGenerated: true },
            autoGenerate: true,
            dependsOn: 'auftrag_id',
            showWhen: 'any',
            readonly: true,
            placeholder: 'Wird automatisch generiert...'
          },
          { name: 'unternehmen_id', label: 'Unternehmen', type: 'select', required: true, options: [], dynamic: true, searchable: true, placeholder: 'Unternehmen suchen und auswählen...', table: 'unternehmen', displayField: 'firmenname', valueField: 'id' },
          { name: 'marke_id', label: 'Marke', type: 'select', required: false, options: [], dynamic: true, searchable: true, placeholder: 'Marke suchen und auswählen...', dependsOn: 'unternehmen_id', table: 'marke', displayField: 'markenname', valueField: 'id' },
          { name: 'auftrag_id', label: 'Auftrag', type: 'select', required: false, options: [], dynamic: true, searchable: true, placeholder: 'Auftrag suchen und auswählen...', dependsOn: 'unternehmen_id', table: 'auftrag', displayField: 'auftragsname', valueField: 'id', filterByMarke: true },
          { name: 'ziele', label: 'Ziele', type: 'textarea', required: false },
          { 
            name: 'art_der_kampagne', 
            label: 'Art der Kampagne', 
            type: 'multiselect', 
            required: false, 
            options: [], 
            dynamic: true, 
            searchable: true, 
            tagBased: true, 
            placeholder: 'Kampagnenarten suchen und auswählen...',
            table: 'kampagne_art_typen',
            displayField: 'name',
            valueField: 'id',
            directQuery: true
          },
          { 
            name: 'kampagne_typ', 
            label: 'Kampagne Typ', 
            type: 'select', 
            required: true, 
            searchable: true,
            placeholder: 'Kampagne-Typ auswählen...',
            options: [
              { value: 'paid', label: 'Paid' },
              { value: 'organic', label: 'Organic' }
            ]
          },
          // Paid-Ziele (nur sichtbar wenn kampagne_typ = 'paid')
          {
            name: 'paid_ziele_ids',
            label: 'Paid Ziele',
            type: 'multiselect',
            required: false,
            options: [],
            dynamic: true,
            searchable: true,
            tagBased: true,
            placeholder: 'Paid-Ziele auswählen...',
            table: 'kampagne_paid_ziele_typen',
            displayField: 'name',
            valueField: 'id',
            relationTable: 'kampagne_paid_ziele',
            relationField: 'ziel_id',
            directQuery: true,
            dependsOn: 'kampagne_typ',
            showWhen: 'paid'
          },
          // Organic-Ziele (nur sichtbar wenn kampagne_typ = 'organic')
          {
            name: 'organic_ziele_ids',
            label: 'Organic Ziele',
            type: 'multiselect',
            required: false,
            options: [],
            dynamic: true,
            searchable: true,
            tagBased: true,
            placeholder: 'Organic-Ziele auswählen...',
            table: 'kampagne_organic_ziele_typen',
            displayField: 'name',
            valueField: 'id',
            relationTable: 'kampagne_organic_ziele',
            relationField: 'ziel_id',
            directQuery: true,
            dependsOn: 'kampagne_typ',
            showWhen: 'organic'
          },
          { name: 'start', label: 'Startdatum', type: 'date', required: false },
          { name: 'deadline', label: 'Deadline', type: 'date', required: false },
          { 
            name: 'drehort_typ_id', 
            label: 'Drehort', 
            type: 'select', 
            required: false, 
            options: [], 
            dynamic: true, 
            searchable: true, 
            placeholder: 'Drehort-Typ auswählen...',
            table: 'drehort_typen',
            displayField: 'name',
            valueField: 'id',
            directQuery: true
          },
          { 
            name: 'drehort_beschreibung', 
            label: 'Drehort Beschreibung', 
            type: 'textarea', 
            required: false,
            dependsOn: 'drehort_typ_id',
            showWhen: 'Vor Ort Produktion'
          },
          { 
            name: 'kampagne_adressen', 
            label: 'Adressen', 
            type: 'custom', 
            customType: 'addresses',
            required: false,
            dependsOn: 'drehort_typ_id',
            showWhen: 'Vor Ort Produktion'
          },
          {
            name: 'status_id',
            label: 'Status',
            type: 'select',
            required: false,
            options: [],
            dynamic: true,
            searchable: true,
            placeholder: 'Status auswählen...',
            table: 'kampagne_status',
            displayField: 'name',
            valueField: 'id',
            directQuery: true
          },
          {
            name: 'plattform_ids',
            label: 'Plattformen',
            type: 'multiselect',
            required: false,
            options: [],
            dynamic: true,
            searchable: true,
            tagBased: true,
            placeholder: 'Plattformen suchen und auswählen...',
            table: 'plattform_typen',
            displayField: 'name',
            valueField: 'id',
            relationTable: 'kampagne_plattformen',
            relationField: 'plattform_id',
            directQuery: true
          },
          {
            name: 'format_ids',
            label: 'Formate',
            type: 'multiselect',
            required: false,
            options: [],
            dynamic: true,
            searchable: true,
            tagBased: true,
            placeholder: 'Formate suchen und auswählen...',
            table: 'format_typen',
            displayField: 'name',
            valueField: 'id',
            relationTable: 'kampagne_formate',
            relationField: 'format_id',
            directQuery: true
          },
          // Mitarbeiter-Zuordnungen
          {
            name: 'cutter_ids',
            label: 'Cutter',
            type: 'multiselect',
            required: false,
            options: [],
            dynamic: true,
            searchable: true,
            tagBased: true,
            placeholder: 'Cutter suchen und auswählen...',
            table: 'benutzer',
            displayField: 'name',
            filterNoKunden: true,
            valueField: 'id',
            relationTable: 'kampagne_mitarbeiter',
            relationField: 'mitarbeiter_id',
            roleValue: 'cutter',
            filterNoKunden: true
          },
          {
            name: 'copywriter_ids',
            label: 'Copywriter',
            type: 'multiselect',
            required: false,
            options: [],
            dynamic: true,
            searchable: true,
            tagBased: true,
            placeholder: 'Copywriter suchen und auswählen...',
            table: 'benutzer',
            displayField: 'name',
            filterNoKunden: true,
            valueField: 'id',
            relationTable: 'kampagne_mitarbeiter',
            relationField: 'mitarbeiter_id',
            roleValue: 'copywriter',
            filterNoKunden: true
          },
          {
            name: 'strategie_ids',
            label: 'Strategie',
            type: 'multiselect',
            required: false,
            options: [],
            dynamic: true,
            searchable: true,
            tagBased: true,
            placeholder: 'Strategie-Mitarbeiter suchen und auswählen...',
            table: 'benutzer',
            displayField: 'name',
            filterNoKunden: true,
            valueField: 'id',
            relationTable: 'kampagne_mitarbeiter',
            relationField: 'mitarbeiter_id',
            roleValue: 'strategie',
            filterNoKunden: true
          },
          {
            name: 'creator_sourcing_ids',
            label: 'Creator Sourcing',
            type: 'multiselect',
            required: false,
            options: [],
            dynamic: true,
            searchable: true,
            tagBased: true,
            placeholder: 'Creator Sourcing Mitarbeiter suchen und auswählen...',
            table: 'benutzer',
            displayField: 'name',
            filterNoKunden: true,
            valueField: 'id',
            relationTable: 'kampagne_mitarbeiter',
            relationField: 'mitarbeiter_id',
            roleValue: 'creator_sourcing',
            filterNoKunden: true
          },
          { name: 'creatoranzahl', label: 'Creator Anzahl', type: 'number', required: false, validation: { type: 'number', min: 1 } },
          { name: 'videoanzahl', label: 'Video Anzahl', type: 'number', required: false, validation: { type: 'number', min: 1 } },
          { name: 'budget_info', label: 'Budget Info', type: 'textarea', required: false }
        ]
      },
      marke: {
        title: 'Neue Marke anlegen',
        fields: [
          { name: 'markenname', label: 'Markenname', type: 'text', required: true, validation: { type: 'text', minLength: 2 } },
          { name: 'logo_file', label: 'Logo', type: 'custom', customType: 'uploader', accept: 'image/png,image/jpeg', multiple: false, required: false },
          { name: 'unternehmen_id', label: 'Unternehmen', type: 'select', required: true, options: [], dynamic: true, searchable: true, placeholder: 'Unternehmen suchen und auswählen...', table: 'unternehmen', displayField: 'firmenname', valueField: 'id' },
          { name: 'webseite', label: 'Webseite', type: 'url', required: false, validation: { type: 'url' } },
          { name: 'branche_ids', label: 'Branchen', type: 'multiselect', required: false, dynamic: true, searchable: true, tagBased: true, placeholder: 'Branchen suchen und hinzufügen...', table: 'branchen', displayField: 'name', valueField: 'id' }
        ]
      },
      auftrag: {
        title: 'Neuen Auftrag anlegen',
        fields: [
          { name: 'art_der_kampagne', label: 'Art der Kampagne', type: 'multiselect', required: false, options: [], dynamic: true, searchable: true, tagBased: true, table: 'kampagne_art_typen', displayField: 'name', valueField: 'id' },
          { name: 'auftragsname', label: 'Auftragsname', type: 'text', required: true, validation: { type: 'text', minLength: 2 } },
          { name: 'unternehmen_id', label: 'Unternehmen', type: 'select', required: true, options: [], dynamic: true, searchable: true, placeholder: 'Unternehmen suchen und auswählen...' },
          { name: 'marke_id', label: 'Marke', type: 'select', required: false, options: [], dynamic: true, searchable: true, placeholder: 'Marke suchen und auswählen...', dependsOn: 'unternehmen_id', table: 'marke', displayField: 'markenname', valueField: 'id' },
          { name: 'status', label: 'Status', type: 'select', required: false, options: ['Beauftragt', 'In Produktion', 'Abgeschlossen', 'Storniert'] },
          { name: 'mitarbeiter_ids', label: 'Lead Mitarbeiter zuweisen', type: 'multiselect', required: false, options: [], dynamic: true, searchable: true, tagBased: true, placeholder: 'Mitarbeiter suchen und auswählen...', table: 'benutzer', displayField: 'name', valueField: 'id', relationTable: 'auftrag_mitarbeiter', relationField: 'mitarbeiter_id' },
          { name: 'ansprechpartner_id', label: 'Ansprechpartner', type: 'select', required: false, options: [], dynamic: true, searchable: true, placeholder: 'Ansprechpartner auswählen...', table: 'ansprechpartner', displayField: 'vorname,nachname,email', valueField: 'id', dependsOn: 'unternehmen_id' },
          { name: 'po', label: 'PO', type: 'text', required: false, placeholder: 'Purchase Order Nummer...' },
          { name: 're_nr', label: 'RE. Nr', type: 'text', required: false, placeholder: 'Rechnungsnummer...' },
          { name: 're_faelligkeit', label: 'RE-Fälligkeit', type: 'date', required: false },
          { name: 'rechnung_gestellt', label: 'Rechnung gestellt', type: 'toggle', required: false },
          { name: 'rechnung_gestellt_am', label: 'Rechnung gestellt am', type: 'date', required: false, placeholder: 'Datum wann Rechnung gestellt wurde', dependsOn: 'rechnung_gestellt' },
          { name: 'ueberwiesen', label: 'Überwiesen', type: 'toggle', required: false },
          { name: 'ueberwiesen_am', label: 'Überwiesen am', type: 'date', required: false, placeholder: 'Datum wann Zahlung überwiesen wurde', dependsOn: 'ueberwiesen' },
          { name: 'kampagnenanzahl', label: 'Kampagnenanzahl', type: 'number', required: false, validation: { type: 'number', min: 1 } },
          { name: 'start', label: 'Startdatum', type: 'date', required: false },
          { name: 'ende', label: 'Enddatum', type: 'date', required: false },
          { name: 'nettobetrag', label: 'Nettobetrag', type: 'number', required: false, validation: { type: 'number', min: 0 } },
          { name: 'ust_prozent', label: 'USt (%)', type: 'number', required: false, validation: { type: 'number', min: 0, max: 100 }, readonly: true, defaultValue: 19 },
          { name: 'ust_betrag', label: 'USt Betrag', type: 'number', required: false, validation: { type: 'number', min: 0 }, readonly: true, calculatedFrom: ['nettobetrag','ust_prozent'] },
          { name: 'bruttobetrag', label: 'Brutto Gesamtbudget', type: 'number', required: false, validation: { type: 'number', min: 0 }, readonly: true, calculatedFrom: ['nettobetrag','ust_betrag'] }
        ]
      },
      kooperation: {
        title: 'Neue Kooperation anlegen',
        fields: [
          { name: 'unternehmen_id', label: 'Unternehmen', type: 'select', required: true, options: [], dynamic: true, searchable: true, placeholder: 'Unternehmen suchen und auswählen...' },
          { name: 'marke_id', label: 'Marke', type: 'select', required: false, options: [], dynamic: true, searchable: true, placeholder: 'Marke auswählen (optional)...', dependsOn: 'unternehmen_id' },
          { name: 'kampagne_id', label: 'Kampagne', type: 'select', required: true, options: [], dynamic: true, searchable: true, placeholder: 'Kampagne suchen und auswählen...', dependsOn: 'unternehmen_id' },
          { name: 'briefing_id', label: 'Briefing', type: 'select', required: false, options: [], dynamic: true, searchable: true, placeholder: 'Briefing wählen...', dependsOn: 'kampagne_id', table: 'briefings', displayField: 'product_service_offer', valueField: 'id' },
          { name: 'creator_id', label: 'Creator', type: 'select', required: true, options: [], dynamic: true, searchable: true, placeholder: 'Creator suchen und auswählen...', dependsOn: 'kampagne_id' },
          { 
            name: 'name', 
            label: 'Name', 
            type: 'text', 
            required: true, 
            validation: { type: 'text', minLength: 2 },
            autoGenerate: true,
            readonly: true,
            placeholder: 'Wird automatisch generiert...'
          },
          { name: 'skript_autor', label: 'Skript schreibt', type: 'select', required: false, options: ['Brand', 'Creator', 'Agentur'] },
          
          // Einkaufspreis
          { name: 'einkaufspreis_netto', label: 'Einkaufspreis Netto', type: 'number', required: false, validation: { type: 'number', min: 0 } },
          { name: 'einkaufspreis_zusatzkosten', label: 'Einkaufspreis Zusatzkosten', type: 'number', required: false, validation: { type: 'number', min: 0 } },
          { name: 'einkaufspreis_ust', label: 'Einkaufspreis USt (19%)', type: 'number', required: false, validation: { type: 'number', min: 0 }, readonly: true, calculatedFrom: ['einkaufspreis_netto', 'einkaufspreis_zusatzkosten'] },
          { name: 'einkaufspreis_gesamt', label: 'Einkaufspreis Gesamt', type: 'number', required: false, validation: { type: 'number', min: 0 }, readonly: true, calculatedFrom: ['einkaufspreis_netto', 'einkaufspreis_zusatzkosten', 'einkaufspreis_ust'] },
          
          // Verkaufspreis
          { name: 'verkaufspreis_netto', label: 'Verkaufspreis Netto', type: 'number', required: false, validation: { type: 'number', min: 0 } },
          { name: 'verkaufspreis_zusatzkosten', label: 'Verkaufspreis Zusatzkosten', type: 'number', required: false, validation: { type: 'number', min: 0 } },
          { name: 'verkaufspreis_ust', label: 'Verkaufspreis USt (19%)', type: 'number', required: false, validation: { type: 'number', min: 0 }, readonly: true, calculatedFrom: ['verkaufspreis_netto', 'verkaufspreis_zusatzkosten'] },
          { name: 'verkaufspreis_gesamt', label: 'Verkaufspreis Gesamt', type: 'number', required: false, validation: { type: 'number', min: 0 }, readonly: true, calculatedFrom: ['verkaufspreis_netto', 'verkaufspreis_zusatzkosten', 'verkaufspreis_ust'] },
          
          { name: 'vertrag_unterschrieben', label: 'Vertrag unterschrieben', type: 'checkbox', required: false },
          { name: 'vertrag_link', label: 'Vertrag Link', type: 'url', required: false, validation: { type: 'url' } },
          { name: 'videoanzahl', label: 'Video Anzahl', type: 'number', required: false, validation: { type: 'number', min: 1 } },
          { name: 'skript_deadline', label: 'Skript Deadline', type: 'date', required: false },
          { name: 'skript_link', label: 'Skript Link', type: 'url', required: false, validation: { type: 'url' } },
          { name: 'content_deadline', label: 'Content Deadline', type: 'date', required: false },
          
          { name: 'status', label: 'Status', type: 'select', required: true, options: ['Todo', 'In progress', 'Done'] }
                ]
      },
      ansprechpartner: {
        title: 'Neuen Ansprechpartner anlegen',
        fields: [
          { name: 'vorname', label: 'Vorname', type: 'text', required: true, validation: { type: 'text', minLength: 2 } },
          { name: 'nachname', label: 'Nachname', type: 'text', required: true, validation: { type: 'text', minLength: 2 } },
          { 
            name: 'unternehmen_id', 
            label: 'Unternehmen', 
            type: 'select', 
            required: false, 
            options: [], 
            dynamic: true,
            searchable: true,
            placeholder: 'Unternehmen suchen und auswählen...',
            table: 'unternehmen',
            displayField: 'firmenname',
            valueField: 'id',
            directQuery: true
          },
          { 
            name: 'marke_ids', 
            label: 'Marken', 
            type: 'multiselect', 
            required: false, 
            options: [], 
            dynamic: true,
            searchable: true,
            tagBased: true,
            placeholder: 'Marken suchen und hinzufügen...',
            dependsOn: 'unternehmen_id',
            table: 'marke',
            displayField: 'markenname',
            valueField: 'id',
            relationTable: 'ansprechpartner_marke',
            relationField: 'marke_id'
          },
          { 
            name: 'position_id', 
            label: 'Position', 
            type: 'select', 
            required: true, 
            options: [], 
            dynamic: true,
            searchable: true,
            placeholder: 'Position suchen und auswählen...',
            table: 'positionen',
            displayField: 'name',
            valueField: 'id',
            directQuery: true
          },
          { name: 'email', label: 'E-Mail', type: 'email', required: false, validation: { type: 'email' } },
          { 
            name: 'telefonnummer',
            nameCountry: 'telefonnummer_land_id',
            label: 'Telefonnummer (mobil)', 
            type: 'phone', 
            required: false,
            defaultCountry: 'Deutschland',
            table: 'eu_laender',
            displayField: 'name_de,vorwahl,iso_code',
            valueField: 'id',
            dynamic: true
          },
          { 
            name: 'telefonnummer_office',
            nameCountry: 'telefonnummer_office_land_id',
            label: 'Telefonnummer (Büro)', 
            type: 'phone', 
            required: false,
            defaultCountry: 'Deutschland',
            table: 'eu_laender',
            displayField: 'name_de,vorwahl,iso_code',
            valueField: 'id',
            dynamic: true
          },
          { name: 'linkedin', label: 'LinkedIn Profil', type: 'url', required: false, validation: { type: 'url' } },
          { name: 'stadt', label: 'Stadt', type: 'text', required: false },
          { name: 'geburtsdatum', label: 'Geburtsdatum', type: 'date', required: false },
          { 
            name: 'sprachen_ids', 
            label: 'Sprachen', 
            type: 'multiselect', 
            required: false, 
            dynamic: true,
            searchable: true,
            tagBased: true,
            placeholder: 'Sprachen suchen und hinzufügen...',
            table: 'sprachen',
            displayField: 'name',
            valueField: 'id',
            relationTable: 'ansprechpartner_sprache',
            relationField: 'sprache_id',
            customField: true
          },
          { name: 'notiz', label: 'Notizen', type: 'textarea', required: false, rows: 4 }
        ]
      },
      briefing: {
        title: 'Neues Briefing anlegen',
        fields: [
          { name: 'product_service_offer', label: 'Produkt/Service/Angebot', type: 'text', required: true, validation: { type: 'text', minLength: 2 }, placeholder: 'Kurzbezeichnung des Produkts/Angebots' },
          { name: 'produktseite_url', label: 'Produktseite URL', type: 'url', required: false, validation: { type: 'url' } },
          { name: 'unternehmen_id', label: 'Unternehmen', type: 'select', required: false, options: [], dynamic: true, searchable: true, placeholder: 'Unternehmen suchen und auswählen...', table: 'unternehmen', displayField: 'firmenname', valueField: 'id', directQuery: true },
          { name: 'marke_id', label: 'Marke', type: 'select', required: false, options: [], dynamic: true, searchable: true, placeholder: 'Marke suchen und auswählen (optional)...', dependsOn: 'unternehmen_id', table: 'marke', displayField: 'markenname', valueField: 'id' },
          { name: 'kampagne_id', label: 'Kampagne', type: 'select', required: false, options: [], dynamic: true, searchable: true, placeholder: 'Kampagne wählen...', dependsOn: 'unternehmen_id', table: 'kampagne', displayField: 'kampagnenname', valueField: 'id' },
          { name: 'assignee_id', label: 'Zugewiesen an', type: 'select', required: false, options: [], dynamic: true, searchable: true, placeholder: 'Mitarbeiter auswählen...', table: 'benutzer', displayField: 'name', valueField: 'id', directQuery: true },
          { name: 'zielgruppe', label: 'Zielgruppe', type: 'textarea', required: false, rows: 3 },
          { name: 'zieldetails', label: 'Zieldetails', type: 'textarea', required: false, rows: 3 },
          { name: 'creator_aufgabe', label: 'Creator Aufgabe', type: 'textarea', required: false, rows: 4 },
          { name: 'usp', label: 'USPs', type: 'textarea', required: false, rows: 3, placeholder: 'Unique Selling Points, durch Komma getrennt oder als Fließtext' },
          { name: 'must_haves', label: 'Must Haves', type: 'textarea', required: false, rows: 4 },
          { name: 'rechtlicher_hinweis', label: 'Rechtlicher Hinweis', type: 'textarea', required: false, rows: 4 },
          { name: 'documents_files', label: 'Dokumente (PDFs, Bilder)', type: 'custom', customType: 'uploader', accept: 'application/pdf,image/*', multiple: true, required: false }
        ]
      },
      rechnung: {
        title: 'Neue Rechnung anlegen',
        fields: [
          { name: 'rechnung_nr', label: 'Rechnungs-Nr', type: 'text', required: true, validation: { type: 'text', minLength: 2 } },
          { name: 'kooperation_id', label: 'Kooperation', type: 'select', required: true, options: [], dynamic: true, searchable: true, placeholder: 'Kooperation wählen...', table: 'kooperationen', displayField: 'name', valueField: 'id' },
          { name: 'unternehmen_id', label: 'Unternehmen', type: 'select', required: true, options: [], dynamic: true, searchable: true, placeholder: 'Unternehmen wird automatisch gesetzt', readonly: true, table: 'unternehmen', displayField: 'firmenname', valueField: 'id' },
          { name: 'auftrag_id', label: 'Auftrag', type: 'select', required: true, options: [], dynamic: true, searchable: true, placeholder: 'Auftrag wird automatisch gesetzt', readonly: true, table: 'auftrag', displayField: 'auftragsname', valueField: 'id' },
          { name: 'kampagne_id', label: 'Kampagne', type: 'select', required: true, options: [], dynamic: true, searchable: true, placeholder: 'Kampagne wird automatisch gesetzt', readonly: true, table: 'kampagne', displayField: 'kampagnenname', valueField: 'id' },
          { name: 'creator_id', label: 'Creator', type: 'select', required: false, options: [], dynamic: true, searchable: true, placeholder: 'Creator wird automatisch gesetzt', readonly: true, table: 'creator', displayField: 'vorname', valueField: 'id' },
          { name: 'videoanzahl', label: 'Video Anzahl (aus Kooperation)', type: 'number', required: false, validation: { type: 'number', min: 0 } },
          { name: 'status', label: 'Status', type: 'select', required: true, options: ['Offen', 'Rückfrage', 'Bezahlt', 'An Qonto gesendet'] },
          { name: 'geprueft', label: 'Geprüft', type: 'toggle', required: false },
          { name: 'gestellt_am', label: 'Gestellt am', type: 'date', required: true },
          { name: 'zahlungsziel', label: 'Zahlungsziel', type: 'date', required: true },
          { name: 'bezahlt_am', label: 'Bezahlt am', type: 'date', required: false },
          { name: 'nettobetrag', label: 'Betrag (Netto)', type: 'number', required: true, validation: { type: 'number', min: 0 } },
          { name: 'zusatzkosten', label: 'Zusatzkosten', type: 'number', required: false, validation: { type: 'number', min: 0 } },
          { name: 'bruttobetrag', label: 'Betrag (Brutto)', type: 'number', required: true, validation: { type: 'number', min: 0 } },
          { name: 'pdf_file', label: 'Rechnungs-PDF', type: 'custom', customType: 'uploader', accept: 'application/pdf', multiple: false, required: false },
          { name: 'belege_files', label: 'Belege (mehrere Dateien)', type: 'custom', customType: 'uploader', accept: 'application/pdf,image/*', multiple: true, required: false }
        ]
      }
    };
    
    return configs[entity] || null;
  }
} 