// StrategieList.js
// Übersicht aller Strategielisten
// Basiert auf BasePaginatedList (Client-seitige Pagination)

import { BasePaginatedList } from '../../core/BasePaginatedList.js';
import { strategieService } from './StrategieService.js';
import { AvatarBubbles } from '../../core/components/AvatarBubbles.js';
import { TableAnimationHelper } from '../../core/TableAnimationHelper.js';
import { KampagneUtils } from '../kampagne/KampagneUtils.js';
import { AutoGeneration } from '../../core/form/logic/AutoGeneration.js';

export class StrategieList extends BasePaginatedList {
  constructor() {
    super('strategie', {
      itemsPerPage: 25,
      headline: 'Strategien',
      breadcrumbLabel: 'Strategien',
      sortField: 'name',
      sortAscending: true,
      paginationContainerId: 'pagination-container-strategie',
      tbodySelector: '#strategien-table-body',
      tableColspan: 6,
      permissionEntity: 'strategie'
    });
    
    // Client-seitige Daten (alle Strategien)
    this.strategien = [];
    
    // Auto-Generierung für Namen
    this.autoGeneration = new AutoGeneration();
  }
  
  // ══════════════════════════════════════════════════════════════════════════
  // IMPLEMENTIERUNG DER ABSTRAKTEN METHODEN
  // ══════════════════════════════════════════════════════════════════════════
  
  /**
   * Client-seitige Pagination: Lädt alle Daten und paginiert im Client
   */
  async loadPageData(page, limit, filters) {
    // Daten einmalig laden wenn noch nicht vorhanden
    if (this.strategien.length === 0 || this._forceReload) {
      this.strategien = await strategieService.getAllStrategien();
      this._forceReload = false;
    }
    
    // Client-seitige Pagination
    const start = (page - 1) * limit;
    const end = start + limit;
    const paginatedData = this.strategien.slice(start, end);
    
    return {
      data: paginatedData,
      total: this.strategien.length
    };
  }
  
  /**
   * Generiert automatisch einen Strategie-Namen aus Kampagnenname
   * Format: "Strategie [Kampagnenname]"
   */
  generateStrategieName(unternehmenDisplay, kampagnenname) {
    if (kampagnenname) {
      return `Strategie ${kampagnenname}`;
    } else if (unternehmenDisplay) {
      return `${unternehmenDisplay} Strategie`;
    }
    return '';
  }

  /**
   * Prüft ob der aktuelle Name ein automatisch generierter Name ist
   */
  isAutoGeneratedName(currentName) {
    if (!currentName || currentName.trim() === '') return true;
    return /^.* Strategie( .*)?$/.test(currentName) || /^Strategie .*$/.test(currentName);
  }
  
  /**
   * Rendert eine einzelne Strategie-Zeile
   */
  renderSingleRow(strategie) {
    const rolle = window.currentUser?.rolle?.toLowerCase();
    const isKunde = rolle === 'kunde' || rolle === 'kunde_editor';

    const unternehmenBubble = strategie.unternehmen 
      ? AvatarBubbles.renderBubbles([{
          name: strategie.unternehmen.firmenname,
          type: 'org',
          id: strategie.unternehmen.id,
          entityType: 'unternehmen',
          logo_url: strategie.unternehmen.logo_url
        }])
      : '-';

    const markeBubble = strategie.marke 
      ? AvatarBubbles.renderBubbles([{
          name: strategie.marke.markenname,
          type: 'org',
          id: strategie.marke.id,
          entityType: 'marke',
          logo_url: strategie.marke.logo_url
        }])
      : '-';

    const kampagneName = KampagneUtils.getDisplayName(strategie.kampagne);

    const createdByBubble = strategie.created_by_user 
      ? AvatarBubbles.renderBubbles([{
          name: strategie.created_by_user.name,
          type: 'person',
          id: strategie.created_by_user.id,
          entityType: 'mitarbeiter',
          profile_image_url: strategie.created_by_user.profile_image_url
        }])
      : '-';

    return `
      <tr class="table-row-clickable" data-strategie-id="${strategie.id}">
        <td class="col-name">
          <a href="#" class="table-link" data-table="strategie" data-id="${strategie.id}">
            ${this.sanitize(strategie.name || 'Ohne Namen')}
          </a>
        </td>
        <td>${unternehmenBubble}</td>
        <td>${markeBubble}</td>
        <td>${kampagneName}</td>
        <td>${createdByBubble}</td>
        <td class="col-actions">
          <div class="actions-dropdown-container" data-entity-type="strategie">
            <button class="actions-toggle" aria-expanded="false" aria-label="Aktionen">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                <path d="M12 8c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm0 2c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0 6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z"/>
              </svg>
            </button>
            <div class="actions-dropdown">
              <a href="#" class="action-item" data-action="view-strategie" data-id="${strategie.id}">
                ${window.ActionsDropdown?.getHeroIcon('view') || ''}
                Details anzeigen
              </a>
              ${!isKunde ? `
                <a href="#" class="action-item" data-action="edit-strategie" data-id="${strategie.id}">
                  ${window.ActionsDropdown?.getHeroIcon('edit') || ''}
                  Bearbeiten
                </a>
                ${window.currentUser?.permissions?.strategie?.can_delete ? `
                  <div class="action-separator"></div>
                  <a href="#" class="action-item action-danger" data-action="delete-strategie" data-id="${strategie.id}">
                    ${window.ActionsDropdown?.getHeroIcon('delete') || ''}
                    Löschen
                  </a>
                ` : ''}
              ` : ''}
            </div>
          </div>
        </td>
      </tr>
    `;
  }
  
  /**
   * Rendert den Shell-Content (Struktur ohne Daten)
   */
  renderShellContent() {
    const rolle = window.currentUser?.rolle?.toLowerCase();
    const isKunde = rolle === 'kunde' || rolle === 'kunde_editor';
    const canCreate = !isKunde && (rolle === 'admin' || window.currentUser?.permissions?.strategie?.can_edit);

    return `
      <div class="list-container">
        <div class="table-filter-wrapper">
          <div class="filter-bar">
            <div class="filter-left">
              <div id="filter-dropdown-container"></div>
            </div>
          </div>
          <div class="table-actions">
            <button class="secondary-btn" data-action="how-to-strategie">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" width="18" height="18">
                <path stroke-linecap="round" stroke-linejoin="round" d="M4.26 10.147a60.438 60.438 0 0 0-.491 6.347A48.62 48.62 0 0 1 12 20.904a48.62 48.62 0 0 1 8.232-4.41 60.46 60.46 0 0 0-.491-6.347m-15.482 0a50.636 50.636 0 0 0-2.658-.813A59.906 59.906 0 0 1 12 3.493a59.903 59.903 0 0 1 10.399 5.84c-.896.248-1.783.52-2.658.814m-15.482 0A50.717 50.717 0 0 1 12 13.489a50.702 50.702 0 0 1 7.74-3.342M6.75 15a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Zm0 0v-3.675A55.378 55.378 0 0 1 12 8.443m-7.007 11.55A5.981 5.981 0 0 0 6.75 15.75v-1.5" />
              </svg>
              How to
            </button>
            ${canCreate ? `
              <button class="primary-btn" data-action="create-strategie">Neue Strategie anlegen</button>
            ` : ''}
          </div>
        </div>

        <div class="table-container">
          <table class="data-table">
            <thead>
              <tr>
                <th class="col-name">Name</th>
                <th>Unternehmen</th>
                <th>Marke</th>
                <th>Kampagne</th>
                <th>Erstellt von</th>
                <th class="col-actions">Aktionen</th>
              </tr>
            </thead>
            <tbody id="strategien-table-body">
              <tr>
                <td colspan="6" style="text-align: center; padding: var(--space-lg); color: var(--text-secondary);">
                  Lade Strategien...
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <div id="pagination-container-strategie"></div>
      </div>
    `;
  }
  
  // ══════════════════════════════════════════════════════════════════════════
  // ÜBERSCHRIEBENE METHODEN
  // ══════════════════════════════════════════════════════════════════════════

  /**
   * Bei jedem Anzeigen der Liste neu laden, damit Kampagnennamen (und andere Relationen) aktuell sind.
   */
  async init() {
    this._forceReload = true;
    await super.init();
  }

  /**
   * Zusätzliche Events binden
   */
  bindAdditionalEvents(signal) {
    // Kampagne umbenannt: Cache invalidieren, damit Kampagnenname in Strategie-Liste aktuell ist
    window.addEventListener('entityUpdated', (e) => {
      if (e.detail.entity === 'kampagne') {
        this.strategien = [];
        this._forceReload = true;
        this.loadDataDebounced(100);
      }
    }, { signal });

    // Create Strategie Button
    document.addEventListener('click', (e) => {
      if (e.target.closest('[data-action="create-strategie"]')) {
        e.preventDefault();
        this.openCreateDrawer();
      }
    }, { signal });
    
    // How to Button
    document.addEventListener('click', (e) => {
      if (e.target.closest('[data-action="how-to-strategie"]')) {
        e.preventDefault();
        this.showHowToModal();
      }
    }, { signal });
    
    // View Strategie
    document.addEventListener('click', (e) => {
      const viewBtn = e.target.closest('[data-action="view-strategie"]');
      if (viewBtn) {
        e.preventDefault();
        const id = viewBtn.dataset.id;
        window.navigateTo(`/strategie/${id}`);
      }
    }, { signal });
    
    // Edit Strategie
    document.addEventListener('click', (e) => {
      const editBtn = e.target.closest('[data-action="edit-strategie"]');
      if (editBtn) {
        e.preventDefault();
        const id = editBtn.dataset.id;
        window.navigateTo(`/strategie/${id}/edit`);
      }
    }, { signal });
    
    // Delete Strategie
    document.addEventListener('click', (e) => {
      const deleteBtn = e.target.closest('[data-action="delete-strategie"]');
      if (deleteBtn) {
        e.preventDefault();
        const id = deleteBtn.dataset.id;
        this.confirmDeleteStrategie(id);
      }
    }, { signal });
    
    // Row Click
    document.addEventListener('click', (e) => {
      const row = e.target.closest('.table-row-clickable');
      if (row && !e.target.closest('.actions-dropdown-container') && !e.target.closest('.table-link')) {
        const id = row.dataset.strategieId;
        if (id) {
          window.navigateTo(`/strategie/${id}`);
        }
      }
    }, { signal });
  }
  
  /**
   * Callback nach erfolgreichem Laden - force Reload bei Updates
   */
  onDataLoaded(data) {
    this._forceReload = false;
  }
  
  // ══════════════════════════════════════════════════════════════════════════
  // STRATEGIE-SPEZIFISCHE METHODEN
  // ══════════════════════════════════════════════════════════════════════════
  
  /**
   * How-to Modal anzeigen
   */
  showHowToModal() {
    if (window.modalSystem) {
      window.modalSystem.open({
        title: 'Wie funktioniert die Strategie?',
        content: `
          <div class="how-to-content">
            <p><strong>1. Strategie erstellen</strong></p>
            <p>Klicke auf "Neue Strategie anlegen" und wähle Unternehmen, Marke und Kampagne aus.</p>
            
            <p><strong>2. Items hinzufügen</strong></p>
            <p>Füge Video-Konzepte, Hooks und andere Elemente zur Strategie hinzu.</p>
            
            <p><strong>3. Mit Kunden teilen</strong></p>
            <p>Kunden können die Strategie einsehen und Feedback geben.</p>
          </div>
        `,
        size: 'medium'
      });
    }
  }
  
  /**
   * Lösch-Bestätigung
   */
  async confirmDeleteStrategie(id) {
    if (window.confirmationModal) {
      const result = await window.confirmationModal.open({
        title: 'Strategie löschen',
        message: 'Möchten Sie diese Strategie wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
        confirmText: 'Löschen',
        cancelText: 'Abbrechen',
        danger: true
      });
      
      if (result?.confirmed) {
        await this.deleteStrategie(id);
      }
    } else {
      if (confirm('Möchten Sie diese Strategie wirklich löschen?')) {
        await this.deleteStrategie(id);
      }
    }
  }
  
  /**
   * Strategie löschen
   */
  async deleteStrategie(id) {
    try {
      const { error } = await window.supabase
        .from('strategie')
        .delete()
        .eq('id', id);
      
      if (error) throw error;
      
      window.toastSystem?.show('Strategie erfolgreich gelöscht', 'success');
      
      // Daten neu laden
      this._forceReload = true;
      this.strategien = [];
      await this.loadData();
      
    } catch (error) {
      console.error('Fehler beim Löschen:', error);
      window.toastSystem?.show('Fehler beim Löschen der Strategie', 'error');
    }
  }
  
  // ══════════════════════════════════════════════════════════════════════════
  // DRAWER METHODEN FÜR STRATEGIE-ERSTELLUNG
  // ══════════════════════════════════════════════════════════════════════════
  
  /**
   * Öffne Create-Drawer für neue Strategie
   */
  openCreateDrawer() {
    console.log('🎯 Öffne Strategie Create-Drawer');
    
    // Bestehenden Drawer entfernen falls vorhanden
    this.closeCreateDrawer();
    
    // Overlay erstellen
    const overlay = document.createElement('div');
    overlay.className = 'drawer-overlay';
    overlay.id = 'strategie-create-drawer-overlay';
    
    // Drawer Panel erstellen
    const panel = document.createElement('div');
    panel.setAttribute('role', 'dialog');
    panel.className = 'drawer-panel';
    panel.id = 'strategie-create-drawer';
    
    // Header
    const header = document.createElement('div');
    header.className = 'drawer-header';
    header.innerHTML = `
      <div>
        <span class="drawer-title">Neue Strategie</span>
        <p class="drawer-subtitle">Erstellen Sie eine neue Strategie für eine Kampagne</p>
      </div>
      <div>
        <button type="button" class="drawer-close-btn" aria-label="Schließen">&times;</button>
      </div>
    `;
    
    // Body mit Formular
    const body = document.createElement('div');
    body.className = 'drawer-body';
    body.innerHTML = window.formSystem.renderFormOnly('strategie');
    
    panel.appendChild(header);
    panel.appendChild(body);
    
    // Events
    overlay.addEventListener('click', () => this.closeCreateDrawer());
    header.querySelector('.drawer-close-btn').addEventListener('click', () => this.closeCreateDrawer());
    
    // Zum DOM hinzufügen
    document.body.appendChild(overlay);
    document.body.appendChild(panel);
    
    // Slide-in Animation
    requestAnimationFrame(() => {
      panel.classList.add('show');
    });
    
    // Formular-Events binden
    window.formSystem.bindFormEvents('strategie', null);
    
    // Custom Submit Handler
    const form = panel.querySelector('#strategie-form');
    if (form) {
      form.onsubmit = async (e) => {
        e.preventDefault();
        await this.handleCreateFormSubmit(form);
      };
      
      // Abbrechen-Button im Formular abfangen
      const cancelBtn = form.querySelector('.mdc-btn--cancel');
      if (cancelBtn) {
        cancelBtn.onclick = (e) => {
          e.preventDefault();
          this.closeCreateDrawer();
        };
      }
    }
  }
  
  /**
   * Schließe Create-Drawer
   */
  closeCreateDrawer() {
    const overlay = document.getElementById('strategie-create-drawer-overlay');
    const panel = document.getElementById('strategie-create-drawer');
    
    if (panel) {
      panel.classList.remove('show');
      setTimeout(() => {
        overlay?.remove();
        panel?.remove();
      }, 300);
    } else {
      overlay?.remove();
    }
  }
  
  /**
   * Handle Submit für Create-Formular
   */
  async handleCreateFormSubmit(form) {
    try {
      const submitData = window.formSystem.collectSubmitData(form);
      
      // Name automatisch generieren falls leer
      if (!submitData.name || submitData.name.trim() === '') {
        const generatedName = await this.autoGeneration.autoGenerateStrategieName(
          submitData.kampagne_id,
          submitData.marke_id,
          submitData.unternehmen_id
        );
        if (generatedName) {
          submitData.name = generatedName;
        }
      }
      
      console.log('📤 Erstelle Strategie:', submitData);
      
      // Strategie erstellen
      const newStrategie = await strategieService.createStrategie(submitData);
      
      if (newStrategie && newStrategie.id) {
        window.toastSystem?.show('Strategie erfolgreich erstellt', 'success');
        
        // Drawer schließen
        this.closeCreateDrawer();
        
        // Zur Detail-Ansicht navigieren
        window.navigateTo(`/strategie/${newStrategie.id}`);
      } else {
        throw new Error('Keine ID zurückgegeben');
      }
      
    } catch (error) {
      console.error('❌ Fehler beim Erstellen:', error);
      window.toastSystem?.show(`Fehler beim Erstellen: ${error.message}`, 'error');
    }
  }
  
  /**
   * showCreateForm für Routing-Kompatibilität (öffnet auch den Drawer)
   */
  showCreateForm() {
    // Zur Liste navigieren und Drawer öffnen
    if (window.location.pathname !== '/strategie') {
      window.navigateTo('/strategie');
      // Drawer nach Navigation öffnen
      setTimeout(() => this.openCreateDrawer(), 100);
    } else {
      this.openCreateDrawer();
    }
  }
  
  /**
   * Override destroy um Cache zu clearen
   */
  destroy() {
    this.strategien = [];
    this.closeCreateDrawer();
    super.destroy();
  }
}

// Exportiere Instanz für globale Nutzung
export const strategieList = new StrategieList();
