// Formular-Konfiguration fuer "kampagne"
// Reine Datendatei, wird von FormConfig.js eingesammelt.

export const kampagneConfig = {
  title: 'Neue Kampagne anlegen',
  fields: [
    { 
      name: 'eigener_name', 
      label: 'Eigener Name', 
      type: 'text', 
      required: false,
      placeholder: 'Optional: Eigenen Kampagnennamen eingeben...'
    },
    { 
      name: 'kampagnenname', 
      label: 'Auto-Kampagnenname', 
      type: 'text', 
      required: false, // Nicht required da automatisch generiert
      validation: { type: 'text', minLength: 2, skipIfAutoGenerated: true },
      autoGenerate: true,
      dependsOn: 'auftrag_id',
      showWhen: 'any',
      readonlyExceptEdit: true,
      placeholder: 'Wird automatisch generiert...'
    },
    { name: 'unternehmen_id', label: 'Unternehmen', type: 'select', required: true, options: [], dynamic: true, searchable: true, placeholder: 'Unternehmen suchen und auswählen...', table: 'unternehmen', displayField: 'firmenname', valueField: 'id' },
    { name: 'marke_id', label: 'Marke', type: 'select', required: false, options: [], dynamic: true, searchable: true, placeholder: 'Marke suchen und auswählen...', dependsOn: 'unternehmen_id', table: 'marke', displayField: 'markenname', valueField: 'id' },
    { name: 'auftrag_id', label: 'Auftrag', type: 'select', required: true, options: [], dynamic: true, searchable: true, placeholder: 'Auftrag suchen und auswählen...', dependsOn: 'unternehmen_id', table: 'auftrag', displayField: 'auftragsname', valueField: 'id', filterByMarke: true },
    { 
      name: 'art_der_kampagne', 
      label: 'Art der Kampagne', 
      type: 'multiselect', 
      required: false, 
      options: [], 
      dynamic: true, 
      searchable: true, 
      tagBased: true, 
      placeholder: 'Kampagnenarten suchen und auswählen...',
      table: 'kampagne_art_typen',
      displayField: 'name',
      valueField: 'id',
      directQuery: true
    },
    { 
      name: 'kampagne_typ', 
      label: 'Kampagne Typ', 
      type: 'select', 
      required: true, 
      searchable: true,
      placeholder: 'Kampagne-Typ auswählen...',
      options: [
        { value: 'paid', label: 'Paid' },
        { value: 'organic', label: 'Organic' },
        { value: 'influencer_posting', label: 'Influencer Posting' }
      ]
    },
    // Paid-Ziele (nur sichtbar wenn kampagne_typ = 'paid')
    {
      name: 'paid_ziele_ids',
      label: 'Paid Ziele',
      type: 'multiselect',
      required: false,
      options: [],
      dynamic: true,
      searchable: true,
      tagBased: true,
      placeholder: 'Paid-Ziele auswählen...',
      table: 'kampagne_paid_ziele_typen',
      displayField: 'name',
      valueField: 'id',
      relationTable: 'kampagne_paid_ziele',
      relationField: 'ziel_id',
      directQuery: true,
      dependsOn: 'kampagne_typ',
      showWhen: 'paid'
    },
    // Organic-Ziele (nur sichtbar wenn kampagne_typ = 'organic')
    {
      name: 'organic_ziele_ids',
      label: 'Organic Ziele',
      type: 'multiselect',
      required: false,
      options: [],
      dynamic: true,
      searchable: true,
      tagBased: true,
      placeholder: 'Organic-Ziele auswählen...',
      table: 'kampagne_organic_ziele_typen',
      displayField: 'name',
      valueField: 'id',
      relationTable: 'kampagne_organic_ziele',
      relationField: 'ziel_id',
      directQuery: true,
      dependsOn: 'kampagne_typ',
      showWhen: 'organic'
    },
    { name: 'start', label: 'Startdatum', type: 'date', required: false },
    // Deadline-Felder Gruppe (3x2 Grid)
    { name: 'deadline_briefing', label: 'Deadline Briefing', type: 'date', required: false, twoCol: true },
    { name: 'deadline_strategie', label: 'Deadline Strategie', type: 'date', required: false, twoCol: true },
    { name: 'deadline_skripte', label: 'Deadline Skripte', type: 'date', required: false, twoCol: true },
    { name: 'deadline_creator_sourcing', label: 'Deadline Sourcing', type: 'date', required: false, twoCol: true },
    { name: 'deadline_video_produktion', label: 'Deadline Video Produktion', type: 'date', required: false, twoCol: true },
    { name: 'deadline_post_produktion', label: 'Deadline Post Produktion', type: 'date', required: false, twoCol: true },
    { 
      name: 'drehort_typ_id', 
      label: 'Drehort', 
      type: 'select', 
      required: false, 
      options: [], 
      dynamic: true, 
      searchable: true, 
      placeholder: 'Drehort-Typ auswählen...',
      table: 'drehort_typen',
      displayField: 'name',
      valueField: 'id',
      directQuery: true
    },
    { 
      name: 'drehort_beschreibung', 
      label: 'Drehort Beschreibung', 
      type: 'textarea', 
      required: false,
      dependsOn: 'drehort_typ_id',
      showWhen: 'Vor Ort Produktion'
    },
    { 
      name: 'kampagne_adressen', 
      label: 'Adressen', 
      type: 'custom', 
      customType: 'addresses',
      required: false,
      dependsOn: 'drehort_typ_id',
      showWhen: 'Vor Ort Produktion'
    },
    {
      name: 'plattform_ids',
      label: 'Plattformen',
      type: 'multiselect',
      required: false,
      options: [],
      dynamic: true,
      searchable: true,
      tagBased: true,
      placeholder: 'Plattformen suchen und auswählen...',
      table: 'plattform_typen',
      displayField: 'name',
      valueField: 'id',
      relationTable: 'kampagne_plattformen',
      relationField: 'plattform_id',
      directQuery: true
    },
    {
      name: 'format_ids',
      label: 'Formate',
      type: 'multiselect',
      required: false,
      options: [],
      dynamic: true,
      searchable: true,
      tagBased: true,
      placeholder: 'Formate suchen und auswählen...',
      table: 'format_typen',
      displayField: 'name',
      valueField: 'id',
      relationTable: 'kampagne_formate',
      relationField: 'format_id',
      directQuery: true
    },
    // Dynamische Kampagnenart-Felder (Container wird durch FormEvents befüllt)
    {
      name: 'kampagnenart_felder_container',
      label: '',
      type: 'custom',
      customType: 'kampagnenart-felder',
      required: false,
      dependsOn: 'art_der_kampagne',
      showWhen: 'any'
    }
  ]
};
