// Formular-Konfiguration fuer "sourcing"
// Reine Datendatei, wird von FormConfig.js eingesammelt.

export const sourcingConfig = {
  title: 'Neue Casting-Liste anlegen',
  fields: [
    { 
      name: 'name', 
      label: 'Name', 
      type: 'text', 
      required: false, 
      autoGenerate: true,
      readonly: true,
      placeholder: 'Wird automatisch generiert...',
      validation: { type: 'text', minLength: 2, skipIfAutoGenerated: true }
    },
    { 
      name: 'unternehmen_id', 
      label: 'Unternehmen', 
      type: 'select', 
      required: true, 
      options: [], 
      dynamic: true, 
      searchable: true, 
      placeholder: 'Unternehmen suchen und auswählen...', 
      table: 'unternehmen', 
      displayField: 'firmenname', 
      valueField: 'id' 
    },
    { 
      name: 'marke_id', 
      label: 'Marke', 
      type: 'select', 
      required: false, 
      options: [], 
      dynamic: true, 
      searchable: true, 
      placeholder: 'Marke suchen und auswählen...', 
      dependsOn: 'unternehmen_id', 
      table: 'marke', 
      displayField: 'markenname', 
      valueField: 'id' 
    },
    {
      name: 'kampagne_id',
      label: 'Kampagne',
      type: 'select',
      required: true,
      options: [],
      dynamic: true,
      searchable: true,
      placeholder: 'Kampagne suchen und auswählen...',
      dependsOn: 'unternehmen_id',
      table: 'kampagne',
      displayField: 'kampagnenname',
      valueField: 'id',
      filterByMarke: true
    },
    {
      // Briefing-Pflicht (Step 1): nur finalisierte Briefings des Unternehmens,
      // bei gesetzter Marke nur Briefings genau dieser Marke. Loader sitzt in
      // CascadeStrategies ('briefing_id:unternehmen_id'); Marke-Wechsel laedt
      // ueber reloadOnChange neu. Leerer Schnitt blockiert den Submit.
      name: 'briefing_id',
      label: 'Briefing',
      type: 'select',
      required: true,
      options: [],
      dynamic: true,
      searchable: true,
      placeholder: 'Briefing suchen und auswählen...',
      dependsOn: 'unternehmen_id',
      reloadOnChange: ['marke_id'],
      table: 'campaign_briefings',
      displayField: 'aktivierung_name',
      valueField: 'id'
    },
    {
      // Optionale 1:1-Verknuepfung (ADR 0010): nur unverknuepfte Konzepte
      // derselben Kampagne mit gleichem Briefing. Loader sitzt in
      // CascadeStrategies ('strategie_id:kampagne_id'); Briefing-Wechsel
      // laedt ueber reloadOnChange neu. Der Service verknuepft nach dem
      // Insert ueber linkCasting (beide Seiten), das Feld laeuft nie direkt
      // in den Insert.
      name: 'strategie_id',
      label: 'Konzept (optional)',
      type: 'select',
      required: false,
      options: [],
      dynamic: true,
      searchable: true,
      placeholder: 'Konzept suchen und auswählen...',
      dependsOn: 'kampagne_id',
      reloadOnChange: ['briefing_id'],
      table: 'strategie',
      displayField: 'name',
      valueField: 'id'
    }
  ]
};
