// Formular-Konfiguration fuer "sourcing"
// Reine Datendatei, wird von FormConfig.js eingesammelt.

export const sourcingConfig = {
  title: 'Neue Creator-Auswahl anlegen',
  fields: [
    { 
      name: 'name', 
      label: 'Name', 
      type: 'text', 
      required: false, 
      autoGenerate: true,
      readonly: true,
      placeholder: 'Wird automatisch generiert...',
      validation: { type: 'text', minLength: 2, skipIfAutoGenerated: true }
    },
    { 
      name: 'unternehmen_id', 
      label: 'Unternehmen', 
      type: 'select', 
      required: true, 
      options: [], 
      dynamic: true, 
      searchable: true, 
      placeholder: 'Unternehmen suchen und auswählen...', 
      table: 'unternehmen', 
      displayField: 'firmenname', 
      valueField: 'id' 
    },
    { 
      name: 'marke_id', 
      label: 'Marke', 
      type: 'select', 
      required: false, 
      options: [], 
      dynamic: true, 
      searchable: true, 
      placeholder: 'Marke suchen und auswählen...', 
      dependsOn: 'unternehmen_id', 
      table: 'marke', 
      displayField: 'markenname', 
      valueField: 'id' 
    },
    { 
      name: 'kampagne_id', 
      label: 'Kampagne', 
      type: 'select', 
      required: true, 
      options: [], 
      dynamic: true, 
      searchable: true, 
      placeholder: 'Kampagne suchen und auswählen...', 
      dependsOn: 'unternehmen_id', 
      table: 'kampagne', 
      displayField: 'kampagnenname', 
      valueField: 'id',
      filterByMarke: true
    }
  ]
};
