-- Additive FLOW-Briefing-Felder. v1 liest die alten Spalten weiter;
-- v2 schreibt die neuen und spiegelt Creator-Bedarf in die Prefix-Spalten.

ALTER TABLE campaign_briefings
  ADD COLUMN IF NOT EXISTS beschreibung text,
  ADD COLUMN IF NOT EXISTS persona_ids uuid[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS nischen text[],
  ADD COLUMN IF NOT EXISTS creator_groessen text[],
  ADD COLUMN IF NOT EXISTS creator_merkmale jsonb,
  ADD COLUMN IF NOT EXISTS voraussetzungen text[],
  ADD COLUMN IF NOT EXISTS hauttyp text,
  ADD COLUMN IF NOT EXISTS haartyp text,
  ADD COLUMN IF NOT EXISTS produkt_erfahrung text,
  ADD COLUMN IF NOT EXISTS aufgabe text,
  ADD COLUMN IF NOT EXISTS art_der_integration text,
  ADD COLUMN IF NOT EXISTS beteiligte_personen text,
  ADD COLUMN IF NOT EXISTS setting text,
  ADD COLUMN IF NOT EXISTS produktionsvoraussetzungen text,
  ADD COLUMN IF NOT EXISTS vorgaben_ausschluesse text,
  ADD COLUMN IF NOT EXISTS umsetzungsideen text,
  ADD COLUMN IF NOT EXISTS referenzen jsonb,
  ADD COLUMN IF NOT EXISTS learnings_text text,
  ADD COLUMN IF NOT EXISTS pflichtinhalte text,
  ADD COLUMN IF NOT EXISTS dos_donts text,
  ADD COLUMN IF NOT EXISTS publish_channels jsonb,
  ADD COLUMN IF NOT EXISTS ad_channels jsonb,
  ADD COLUMN IF NOT EXISTS videolaengen text[],
  ADD COLUMN IF NOT EXISTS videolaenge_text text,
  ADD COLUMN IF NOT EXISTS funnel_stufen text[],
  ADD COLUMN IF NOT EXISTS paid_objectives text[],
  ADD COLUMN IF NOT EXISTS content_ziele text[],
  ADD COLUMN IF NOT EXISTS cta text,
  ADD COLUMN IF NOT EXISTS ziel_url text,
  ADD COLUMN IF NOT EXISTS hook_vorgaben text,
  ADD COLUMN IF NOT EXISTS plattformmechanik text,
  ADD COLUMN IF NOT EXISTS trendkontext text,
  ADD COLUMN IF NOT EXISTS posting_anforderungen text,
  ADD COLUMN IF NOT EXISTS freigabeprozess text,
  ADD COLUMN IF NOT EXISTS veroeffentlichungszeitraum text,
  ADD COLUMN IF NOT EXISTS nutzung_markenkanal boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS nutzung_paid_media boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS nutzung_creator_kanal boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS nutzung_whitelisting boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS nutzungsdauer text,
  ADD COLUMN IF NOT EXISTS rohmaterial text,
  ADD COLUMN IF NOT EXISTS verhandlungshinweis text;

COMMENT ON COLUMN campaign_briefings.verhandlungshinweis IS
  'Interner Hinweis fuer Vertragsverhandlung. Nicht im Creator-PDF.';
